import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'node:path';

// One shared JS/CSS build for every tenant. Tenant-specific HTML shells,
// manifests, icons and service-worker copies are generated after the build by
// `npm run build:shells` (scripts/build-shells.ts) from tenants/*/business.json.
export default defineConfig({
  base: '/',
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectRegister: null, // registered manually with a per-tenant scope
      manifest: false, // per-tenant manifests are generated by build:shells
      injectManifest: {
        globPatterns: ['assets/**/*.{js,css,woff2}'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
      },
      devOptions: { enabled: false },
    }),
  ],
  resolve: { alias: { '@': path.resolve(import.meta.dirname, 'src') } },
  build: {
    target: 'es2022',
    sourcemap: true,
    chunkSizeWarningLimit: 900,
  },
  server: { port: 5173, strictPort: true },
  preview: { port: 4173, strictPort: true },
});
