#!/usr/bin/env bash
# Local dev/E2E environment without Docker:
#   local Postgres (migrations + generated seed) + local-stack HTTP emulator
#   + demo staff accounts. Writes .env.local for Vite and the scripts.
set -euo pipefail
cd "$(dirname "$0")/../.."
export PGPASSWORD="${PGPASSWORD:-postgres}"
DB="${LOCAL_DEV_DB:-barbershop_dev}"
PORT="${LOCAL_STACK_PORT:-54321}"
npx tsx scripts/tenant/build-seed.ts >/dev/null
LOCAL_DB_NAME="$DB" scripts/db/reset-local.sh --seed
rm -rf .local-stack/storage
KEYS=$(npx tsx -e "import {localKeys} from './tools/local-stack/jwt.ts'; const k=localKeys(process.env.LOCAL_JWT_SECRET ?? 'local-stack-jwt-secret-change-me-0123456789'); console.log(k.anon+' '+k.service)")
ANON=${KEYS% *}; SERVICE=${KEYS#* }
cat > .env.local <<ENV
# generated by tools/local-stack/local-up.sh — LOCAL EMULATOR, not a Supabase project
VITE_SUPABASE_URL=http://localhost:${PORT}
VITE_SUPABASE_ANON_KEY=${ANON}
SUPABASE_URL=http://localhost:${PORT}
SUPABASE_ANON_KEY=${ANON}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE}
LOCAL_DATABASE_URL=postgres://postgres:${PGPASSWORD}@localhost:5432/${DB}
ENV
echo "✓ .env.local written (local emulator at http://localhost:${PORT})"
