/**
 * Local dev/E2E environment without Docker and without bash:
 *   local PostgreSQL (migrations + generated seed) + writes .env.local for Vite and the scripts.
 *   npm run local:up           (then: npm run local:stack, npm run local:staff, npm run dev)
 */
import { spawnSync } from 'node:child_process';
import { rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { databaseUrl, resetDatabase, ROOT } from './db.ts';
import { localKeys } from './jwt.ts';

const DB = process.env.LOCAL_DEV_DB ?? 'barbershop_dev';
const PORT = process.env.LOCAL_STACK_PORT ?? '54321';

const seed = spawnSync(process.execPath, ['--import', 'tsx', 'scripts/tenant/build-seed.ts'], { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] });
if (seed.status !== 0) process.exit(seed.status ?? 1);

const n = await resetDatabase(DB, true);
console.log(`local db '${DB}' ready (${n} migrations)`);
rmSync(path.join(ROOT, '.local-stack/storage'), { recursive: true, force: true });

const keys = localKeys(process.env.LOCAL_JWT_SECRET ?? 'local-stack-jwt-secret-change-me-0123456789');
writeFileSync(
  path.join(ROOT, '.env.local'),
  [
    '# generated by tools/local-stack/local-up.ts — LOCAL EMULATOR, not a Supabase project',
    `VITE_SUPABASE_URL=http://localhost:${PORT}`,
    `VITE_SUPABASE_ANON_KEY=${keys.anon}`,
    `SUPABASE_URL=http://localhost:${PORT}`,
    `SUPABASE_ANON_KEY=${keys.anon}`,
    `SUPABASE_SERVICE_ROLE_KEY=${keys.service}`,
    `LOCAL_DATABASE_URL=${databaseUrl(DB)}`,
    '',
  ].join('\n'),
);
console.log(`✓ .env.local written (local emulator at http://localhost:${PORT})`);
