/**
 * npm run seed:build — generates supabase/seed.sql from tenants/<slug>/ with
 * "is_demo": true. Demo data lives ONLY in tenants/ + seed.sql, never in src/.
 * Media in the seed points to the static copies emitted by build:shells
 * (/s/<slug>/media/...), so a seeded DB works without Storage uploads.
 * Staff users are not created here (see `npm run local:up` / tenant:member).
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ROOT, listTenantSlugs, loadBusiness, normalize, printIssues, validateBusiness } from './lib.ts';
import { mediaPathsFrom, mediaPlan } from './media.ts';

const parts: string[] = [
  '-- GENERATED by `npm run seed:build` from tenants/*/business.json (is_demo = true).',
  '-- Do not edit by hand. Contains explicitly flagged demo data only.',
  "set client_min_messages = warning;",
];
for (const slug of await listTenantSlugs()) {
  const { biz, dir, issues } = await loadBusiness(slug);
  if (!biz) {
    printIssues(slug, issues);
    process.exit(1);
  }
  if (!biz.is_demo) continue;
  const more = await validateBusiness(biz, dir, slug);
  if (!printIssues(slug, more)) process.exit(1);
  const plan = await mediaPlan(biz, dir);
  const cfg = normalize(biz, mediaPathsFrom(plan, `/s/${slug}/media/`));
  parts.push(`\n-- ${slug}`);
  parts.push(`select public.pipeline_publish_tenant($cfg$${JSON.stringify(cfg)}$cfg$::jsonb, true, false);`);
  if (biz.demo?.bookings.length) {
    parts.push(
      `select public.pipeline_seed_demo_bookings('${slug}', $d$${JSON.stringify(biz.demo.bookings)}$d$::jsonb)\n` +
        `where not exists (select 1 from public.bookings b join public.tenants t on t.id = b.tenant_id where t.slug = '${slug}');`,
    );
  }
  console.log(`  ✓ ${slug}: ${cfg.services.length} services, ${cfg.barbers.length} barbers, ${biz.demo?.bookings.length ?? 0} demo bookings`);
}
await writeFile(path.join(ROOT, 'supabase/seed.sql'), parts.join('\n') + '\n');
console.log('✓ supabase/seed.sql written');
